// apps/react-tracker/src/components/shared/FooterComponent.tsx
export const FooterComponent = () => {
  return (
    <footer className="mt-auto py-6 border-t border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-900">
      <div className="max-w-5xl mx-auto px-4 text-center">
        <p className="text-gray-600 dark:text-slate-400 text-sm">
          &copy; {new Date().getFullYear()} Task Tracker. Built with React and PrimeReact.
        </p>
      </div>
    </footer>
  );
};

// vue-tracker/src/components/shared/FooterComponent.vue
<script setup lang="ts">
// Footer component with minimal styling
</script>

<template>
  <footer class="mt-auto py-6 border-t border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-900">
    <div class="max-w-5xl mx-auto px-4 text-center">
      <p class="text-gray-600 dark:text-slate-400 text-sm">
        &copy; {{ new Date().getFullYear() }} Task Tracker. Built with Vue 3 and PrimeVue.
      </p>
    </div>
  </footer>
</template>
