// apps/react-tracker/src/components/tasks/TaskForm.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { v4 as uuidv4 } from 'uuid';
import { Button } from 'primereact/button';
import { Calendar } from 'primereact/calendar';
import { Checkbox } from 'primereact/checkbox';
import { taskService } from '../../services/task.service';
import type { Task } from '../../interfaces/task.interface';

export const TaskForm = () => {
  const navigate = useNavigate();

  const [taskText, setTaskText] = useState('');
  const [taskDate, setTaskDate] = useState<Date>(new Date());
  const [taskReminder, setTaskReminder] = useState(false);

  const cancelAddTask = () => {
    navigate('/');
  };

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!taskText || !taskDate) {
      alert('Please fill all fields');
      return;
    }

    const newTask: Task = {
      id: uuidv4(),
      text: taskText,
      day: taskDate,
      reminder: taskReminder,
    };

    try {
      const taskPayload = {
        ...newTask,
        day: newTask.day instanceof Date ? newTask.day.toISOString() : newTask.day,
      };
      await taskService.addTask(taskPayload as Task);
      navigate('/');
    } catch (error) {
      console.error('Failed to add task:', error);
      alert('Failed to add task. Please try again.');
    }
  };

  return (
    <div className="px-6 py-8">
      <h2 className="text-2xl font-bold text-gray-800 dark:text-slate-100 mb-6">Add New Task</h2>
      <form
        onSubmit={onSubmit}
        data-test-id="add-task-form"
        className="space-y-6 bg-white dark:bg-slate-900 p-6 rounded-lg shadow-md"
      >
        <div className="form-field">
          <label
            htmlFor="text"
            data-testid="label-task"
            className="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2"
          >
            Task Description
          </label>
          <input
            id="text"
            value={taskText}
            onChange={(e) => setTaskText(e.target.value)}
            type="text"
            placeholder="Enter task description"
            data-test-id="input-task"
            className="p-inputtext p-component w-full"
          />
        </div>

        <div className="form-field">
          <label
            htmlFor="date"
            data-test-id="label-date"
            className="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2"
          >
            Due Date
          </label>
          <Calendar
            id="date"
            value={taskDate}
            onChange={(e) => setTaskDate(e.value as Date)}
            showIcon
            className="w-full"
            showTime
            hourFormat="12"
          />
        </div>

        <div className="form-field flex items-center gap-3 p-4 bg-gray-50 dark:bg-slate-800 rounded-lg">
          <Checkbox
            inputId="reminder"
            checked={taskReminder}
            onChange={(e) => setTaskReminder(e.checked ?? false)}
            data-test-id="input-reminder"
            className="w-5 h-5"
          />
          <label
            htmlFor="reminder"
            data-test-id="label-reminder"
            className="text-sm font-medium text-gray-700 dark:text-slate-300 cursor-pointer"
          >
            Set Reminder
          </label>
        </div>

        <div className="flex gap-4 pt-4">
          <Button
            className="flex-1"
            data-test-id="input-cancel-task"
            label="Cancel"
            id="cancelButton"
            onClick={cancelAddTask}
            severity="secondary"
            outlined
            type="button"
          />
          <Button
            className="flex-1"
            data-test-id="input-save-task"
            label="Save Task"
            id="submitButton"
            type="submit"
            severity="success"
            icon="pi pi-check"
          />
        </div>
      </form>
    </div>
  );
};

// vue-tracker/src/components/tasks/TaskForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { v4 as uuidv4 } from 'uuid';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import DatePicker from 'primevue/datepicker';
import Checkbox from 'primevue/checkbox';
import { taskService } from '../../services/task.service';
import type { Task } from '../../interfaces/task.interface';

const router = useRouter();

const taskText = ref('');
const taskDate = ref<Date>(new Date());
const taskReminder = ref(false);

const cancelAddTask = () => {
  router.push('/');
};

const onSubmit = async () => {
  if (!taskText.value || !taskDate.value) {
    alert('Please fill all fields');
    return;
  }

  const newTask: Task = {
    id: uuidv4(),
    text: taskText.value,
    day: taskDate.value,
    reminder: taskReminder.value,
  };

  try {
    await taskService.addTask(newTask);
    router.push('/');
  } catch (error) {
    console.error('Failed to add task:', error);
    alert('Failed to add task. Please try again.');
  }
};
</script>

<template>
  <div class="px-6 py-8">
    <h2 class="text-2xl font-bold text-gray-800 dark:text-slate-100 mb-6">Add New Task</h2>
    <form
      @submit.prevent="onSubmit"
      data-test-id="add-task-form"
      class="space-y-6 bg-white dark:bg-slate-900 p-6 rounded-lg shadow-md"
    >
      <div class="form-field">
        <label for="text" data-testid="label-task" class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2">
          Task Description
        </label>
        <InputText
          id="text"
          v-model="taskText"
          type="text"
          placeholder="Enter task description"
          data-test-id="input-task"
          class="w-full"
        />
      </div>

      <div class="form-field">
        <label for="date" data-test-id="label-date" class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2">
          Due Date
        </label>
        <DatePicker
          id="date"
          v-model="taskDate"
          :showIcon="true"
          appendTo="body"
          class="w-full"
          showTime
          hourFormat="12"
        />
      </div>

      <div class="form-field flex items-center gap-3 p-4 bg-gray-50 dark:bg-slate-800 rounded-lg">
        <Checkbox
          id="reminder"
          v-model="taskReminder"
          :binary="true"
          data-test-id="input-reminder"
          class="w-5 h-5"
        />
        <label
          for="reminder"
          data-test-id="label-reminder"
          class="text-sm font-medium text-gray-700 dark:text-slate-300 cursor-pointer"
        >
          Set Reminder
        </label>
      </div>

      <div class="flex gap-4 pt-4">
        <Button
          class="flex-1"
          data-test-id="input-cancel-task"
          label="Cancel"
          id="cancelButton"
          @click="cancelAddTask"
          severity="secondary"
          outlined
          type="button"
        />
        <Button
          class="flex-1"
          data-test-id="input-save-task"
          label="Save Task"
          id="submitButton"
          type="submit"
          severity="success"
          icon="pi pi-check"
        />
      </div>
    </form>
  </div>
</template>
